// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAL17cgmsYUa75bA4WCQUn7-ngZFAW2PgY',
    appId: '1:592727043147:web:597a7ccb212f23786d31ce',
    messagingSenderId: '592727043147',
    projectId: 'smart-home-d0874',
    authDomain: 'smart-home-d0874.firebaseapp.com',
    storageBucket: 'smart-home-d0874.firebasestorage.app',
    measurementId: 'G-0W6PBXXSC1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgoKNHO-a8ZcHrUrEfJCLV7CwpZt2bxu8',
    appId: '1:592727043147:android:fc2454368de2703f6d31ce',
    messagingSenderId: '592727043147',
    projectId: 'smart-home-d0874',
    storageBucket: 'smart-home-d0874.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWGujzmNL2fgMYg-zWJQVzh6EASlJh0go',
    appId: '1:592727043147:ios:2e80fbb30e8adebc6d31ce',
    messagingSenderId: '592727043147',
    projectId: 'smart-home-d0874',
    storageBucket: 'smart-home-d0874.firebasestorage.app',
    iosBundleId: 'com.example.smartHome1',
  );
}
